version: '0.0.1'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - zookeeper
      - kafka
  kafka:
    image: "wurstmeister/kafka"
    ports:
     - "9092:9092"
    hostname: kafka
    links:
     - zookeeper
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=kafka
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_PORT=9092
     - KAFKA_CREATE_TOPICS="pawk:1:1,test:1:1"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
